version: '3'
services:
  webapp:
    build: .
    environment:
      DB_MYSQL_HOST: mysqldb
      DB_MYSQL_PORT: 3306
      DB_MYSQL_NAME: "testdb"
      DB_MYSQL_USER: root
      DB_MYSQL_PASS: "123456aA"
    deploy:
     resources:
       limits:
         memory: 200M
       reservations:
         memory: 100M
    ports:
     - "80:8080"
    links:
     - "database"
  mysqldb:
    image: mysql/mysql-server:5.7
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M
    expose:
     - "3306"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: "123456aA"
